# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Ryotaro SAKAMOTO"                                # Your name
  description: "graduate student of University of Tokyo"   # A brief slogan (optional)
  image: img/profile.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Biography"
        href: biography/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "blog"
        href: blog/index.qmd
    
    # your social media handles
    right:
      - icon: twitter
        href: https://twitter.com
      - icon: envelope
        aria-label: email
        href: "sakamotoryotaro582@g.ecc.u-tokyo.ac.jp"  
  
  

  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">2023 Ryotaro SAKAMOTO</span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@200;400&display=swap" rel="stylesheet">
    link-citations: yes
    mainfont: Noto Sans JP
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true