---
title: "日本史"
author: "Ryotaro SAKAMOTO"
date: "2024-12-04"
categories: [reading, history]
draft: true
---

# 詳説　日本史

小学生以来の日本史の勉強。印象に残った箇所をメモ程度に記す。

## 地方政治の展開と武士

**受領と負名**

> 戸籍に記載された成人男性（正丁）を中心に課税する律令体制の原則は崩れ、土地を基礎に受領が負名（「名」という徴税単位の請「負」人）から徴税する体制ができていった。（p79）

受領：国司の最上席者（一国の財産を前任者から引き継ぐことから） 負名： 田堵：

受領も公領の経営は田堵との契約であり、国司交代以外は目代と在庁官人に任せ、普段は在京する（遙任）することが増えた。

-   私財を出して朝廷の儀式や造宮・造寺などの費用を請け負う＝成功（じょうごう）「功」（国家への貢献）を「成」す。
-   成功によって同じポストに再任されたり、任期を延長される＝重任（ちょうにん）

> 開発領主の中には、国衙の干渉を免れるために所領を中央の権力者に寄進し、権力者を領主と仰ぐ荘園として自らは荘官となるものも現れた。

荘園の中には、官物や臨時雑役の免除（不輸）や検田使などの国衙の死者の立ち入りを認めない（不入）荘園も増えていった。 ⇒受領から中央への税収が減少したため、天皇家や摂関家、大寺社は積極的に寄進を受け入れた。（荘園が拡大した理由）

**地方の反乱と武士の成長**

国司の子孫や地方豪族を鎮圧するために政府から押領使や追捕使に任じされた中・下級貴族の中には、そのまま在庁官人として現地に残り、武士（兵）となるものが現れた。

-   平将門
-   藤原純友

朝廷や貴族も武士を侍として奉仕させるようになった。

> 中央貴族の血筋を引く清和源氏や桓武平氏を棟梁と仰ぐようになり、源平両氏は地方武士団を広く組織した武家（軍事貴族）を形成して、大きな勢力を築くようになった。

源氏は、 - 平忠常の乱 - 前九年合戦・後三年合戦

を経て東国の武士団と主従関係を強めていく。

**ヨーロッパ人の東アジア進出** 大交易時代の背景には、宗教改革によってカトリック内部から改革の必要性を痛感していた宣教師の存在、拡大していたイスラーム世界への対処があった。

-   スペイン⇒マニラ
-   ポルトガル⇒マカオ

**南蛮貿易とキリスト教**

当時神谷寿禎による灰吹法の伝来によって石見大森銀山からの銀の生産量が飛躍的に増大していた。日本は、ポルトガル人を介して、銀を売って中国産の生糸を買っていた。また、ポルトガルが銀を欲していたのは、ポトシ銀山の銀を背景に東アジア貿易に参加したスペインに対抗するため。

<https://www.pref.shimane.lg.jp/life/bunka/bunkazai/ginzan/outline/outline_08.html>

島根県の石見銀山の歴史ページめっちゃ面白い。

-   灰吹法による銀の生産拡大は大内氏への献上銀が毎年16kgから80kgに急増するほど！
― 　ソーマ銀の由来は佐摩村
-   15世紀後半から16世紀初頭の石見銀山の開発以前に、日本は既に東アジアにおける銅・鉄を中心とする金属資源の供給国であり、その供給経路を使うことができた
-   石見銀山をめぐる大名の抗争

> ポルトガル船は布教を許可した大名領にのみ入港したので、貿易の利益を求め、キリスト教を保護し、自ら入信するキリシタン大名が現れた。

貿易と宣教が一体となっていたのがミソ。

ヴァリニャーニの勧めによって天正遣欧使節が派遣される。これは、日本人にヨーロッパを見せると同時にヨーロッパに日本を知らしめるという目的があったらしい（wiki）。
（ヴァリニャーニは織田信長に黒人奴隷を献上した。これが近年話題になった弥助。）

織田信長
足利義明を京都から追放して室町幕府を滅ぼした。

豊臣秀吉
朝廷から関白に任じられた後、惣無事令を出し、違反したとして四国平定（長曾我部）、九州平定（島津）、小田原平定（北条）を実施。

>関白は五摂家（一条・二条・九条・近衛・鷹司）というTOP藤原氏でなければなれない。ここは近衛家の養子にしてもらったのである。

- 太閤検地：土地の面積表示を「町・段・畝・歩」に統一、枡の容量も京枡に統一し、石高制を確立
- 刀狩：農民から武器を没収
― 人掃令：諸身分を確定させ、兵農分離を確立



禁中並公家諸法度
語感だけで覚えていたが、武家諸法度の公家verだと思えばわかりやすい。

鎖国政策の理由

- キリスト教の禁教政策
- 貿易に関係している西国の大名が富強になるのを恐れて、貿易を幕府の統括下に置こうとした


なぜ長崎なのか？

- 長崎がもともと貿易の拠点だったから
- 幕府から**一番遠い**直轄領（天領）だから

この二つは関係していて、秀吉が九州平定した際に、長崎がキリシタン大名の大村純忠からイエズス会に寄進されているのを知って危機感を持ち、長崎を直轄領にした。

<https://www.y-history.net/appendix/wh0801-119.html>





















